theme: minima
title: My First Github Page
author: Mohnish Thandassery
email: mohnishthandasserycode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mohnish Thandassery's first Github Page.

# social links
twitter_username: Mohnish_13295 # DO NOT include the @ character, or else the build will fail!
github_username:  mohnishthandassery # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
